### ISSUE TITLE
Cannot submit bid

### ISSUE THREAD

**Issue by sw882882** [HMellor/auction-website#19]
**Describe the bug**
<img width="688" alt="image" src="https://user-images.githubusercontent.com/67698926/168755753-d7ee4655-8dea-4bfc-8423-86237a204b02.png">
getting this error after following the directions in readme, then trying to submit a bid. 
**To Reproduce**
1. follow the directions in readme
2. try to submit a bid
**Expected behavior**
It should properly get data from firebase and submit the bid

**Screenshots**
<img width="926" alt="image" src="https://user-images.githubusercontent.com/67698926/168757332-5fce453b-af4d-4e81-b101-fd4e043ed9eb.png">
rules page in firebase

**Desktop (please complete the following information):**
 - OS: MacOS, Arch linux
 - Browser brave [Version 1.37.116 Chromium: 100.0.4896.127 (Official Build) (x86_64)](https://brave.com/latest/)

**Additional context**
I tried to troubleshoot it with my minimal JS knowledge, and it seems to not be able to get proper information other than undefined from the bid data collections. Sometimes it does not even create a collection, maybe that is the issue. (I may be completely wrong, I don't know much about JS or web development)

**Comment by HMellor** [comment]
It looks like `doc.data()` is returning undefined and the JS error is saying that it cannot read `00007` from this undefined return value. In the Firebase console, does the structure of your Firestore Database look like this:

![image](https://user-images.githubusercontent.com/19981378/168835663-a87deb38-9703-4a89-9426-f9d0a5dc741d.png)

If not, have you run `resetAll()` as admin? 

If yes:
- Have you added any auctions to `auctions.js` since you last ran `resetAll()`? If you have then this might effectively be an index out of range error.
- Were there any errors in the console during the setup that could point towards why the Firestore Database isn't configured correctly?

**Comment by sw882882** [comment]
ResetAll() had issues with auction-live, so i manually created a collection for it and after that it worked! Thanks for the help
